// web/src/features/auth/ui/LoginView.tsx
import {
	UiButton,
	UiCheckbox,
	UiInput,
	UiLoader,
	UiSegmentedControl,
} from '@/ui-kit';
import { useLogin } from '../hooks/useLogin';
import './LoginView.css';

const authModeOptions = [
	{ value: 'signIn', label: 'Sign in' },
	{ value: 'signUp', label: 'Sign up' },
] as const;

export default function LoginView() {
	const {
		mode,
		setMode,
		form,
		updateField,
		errors,
		loading,
		errorMessage,
		submit,
	} = useLogin();

	const signingIn = mode === 'signIn';
	return (
		<main className='auth-page'>
			<section className='auth-card'>
				<p className='auth-caption'>Mini Media</p>
				<div className='auth-header'>
					<h1>{signingIn ? 'Welcome back' : 'Create account'}</h1>
					<UiSegmentedControl
						value={mode}
						onChange={setMode}
						options={authModeOptions}
						disabled={loading}
					/>
				</div>
				<p className='auth-subtitle'>
					{signingIn
						? 'Sign in to continue to your dashboard.'
						: 'Create a new account to get started.'}
				</p>
				<form
					className='auth-form'
					noValidate
					onSubmit={(event) => {
						event.preventDefault();
						void submit();
					}}
				>
					<div
						className={`auth-signup-transition ${signingIn ? '' : 'auth-signup-transition--open'}`}
						aria-hidden={signingIn}
					>
						<div className='auth-signup-extra'>
							<UiInput
								value={form.fullName}
								onChange={(value) => updateField('fullName', value)}
								label='Full name'
								placeholder='Иванов Иван Иванович'
								autoComplete='name'
								error={errors.fullName}
								disabled={signingIn || loading}
							/>
							<div className='auth-field'>
								<label className='auth-field__label' htmlFor='birthDate'>
									Date of birth
								</label>
								<input
									id='birthDate'
									value={form.birthDate}
									onChange={(event) => updateField('birthDate', event.target.value)}
									className='auth-field__input'
									type='date'
									autoComplete='bday'
									disabled={signingIn || loading}
									aria-invalid={Boolean(errors.birthDate)}
									aria-describedby={errors.birthDate ? 'birthDate-error' : undefined}
								/>
								{errors.birthDate && (
									<span id='birthDate-error' className='auth-field__error'>
										{errors.birthDate}
									</span>
								)}
							</div>
						</div>
					</div>
					<UiInput
						value={form.email}
						onChange={(value) => updateField('email', value)}
						label={signingIn ? 'Email' : 'Login (email)'}
						placeholder='you@example.com'
						autoComplete='email'
						error={errors.email}
						disabled={loading}
					/>
					<UiInput
						value={form.password}
						onChange={(value) => updateField('password', value)}
						label={signingIn ? 'Password' : 'Create password'}
						type='password'
						placeholder={signingIn ? 'Enter your password' : 'Choose a password'}
						autoComplete={signingIn ? 'current-password' : 'new-password'}
						error={errors.password}
						disabled={loading}
					/>
					{signingIn && (
						<UiCheckbox
							checked={form.rememberMe}
							onChange={(value) => updateField('rememberMe', value)}
							label='Remember me'
							disabled={loading}
						/>
					)}
					<UiButton type='submit' loading={loading} fullWidth>
						{loading
							? signingIn
								? 'Signing in...'
								: 'Creating account...'
							: signingIn
								? 'Sign in'
								: 'Sign up'}
					</UiButton>
					{loading && (
						<div className='loading-state'>
							<UiLoader size='sm' label='Authorizing user' />
							<span>Authorizing...</span>
						</div>
					)}
					{errorMessage && (
						<p className='error' role='alert'>
							{errorMessage}
						</p>
					)}
				</form>
			</section>
		</main>
	);
}

// web/src/features/auth/ui/LoginView.vue
<script setup lang="ts">
import {
  UiButton,
  UiCheckbox,
  UiInput,
  UiLoader,
  UiSegmentedControl,
} from '@/ui-kit';
import { useLogin } from '@/features/auth/composables/useLogin';
import { createAutoHeightTransitionHooks } from '@/shared/utils/autoHeightTransition';

const { mode, form, errors, loading, notice, errorMessage, submit } = useLogin();
const transition = createAutoHeightTransitionHooks();

const authModeOptions = [
  { value: 'signIn', label: 'Sign in' },
  { value: 'signUp', label: 'Sign up' },
] as const;
</script>

<template>
  <main class="auth-page">
    <section class="auth-card">
      <p class="auth-caption">Mini Media</p>
      <div class="auth-header">
        <h1>{{ mode === 'signIn' ? 'Welcome back' : 'Create account' }}</h1>

        <UiSegmentedControl v-model="mode" :options="authModeOptions" />
      </div>

      <p class="auth-subtitle">
        {{
          mode === 'signIn'
            ? 'Sign in to continue to your dashboard.'
            : 'Create a new account to get started.'
        }}
      </p>

      <form class="auth-form" @submit.prevent="submit">
        <Transition
          @before-enter="transition.onBeforeEnter"
          @enter="transition.onEnter"
          @after-enter="transition.onAfterEnter"
          @before-leave="transition.onBeforeLeave"
          @leave="transition.onLeave"
          @after-leave="transition.onAfterLeave"
        >
          <div v-if="mode === 'signUp'" class="auth-signup-extra">
            <UiInput
              v-model="form.fullName"
              label="Full name"
              placeholder="Иванов Иван Иванович"
              autocomplete="name"
              :error="errors.fullName"
            />

            <div class="auth-field">
              <label class="auth-field__label" for="birthDate">Date of birth</label>
              <input
                id="birthDate"
                v-model="form.birthDate"
                class="auth-field__input"
                type="date"
                autocomplete="bday"
              />
              <span v-if="errors.birthDate" class="auth-field__error">
                {{ errors.birthDate }}
              </span>
            </div>
          </div>
        </Transition>

        <UiInput
          v-model="form.email"
          :label="mode === 'signIn' ? 'Email' : 'Login (email)'"
          placeholder="you@example.com"
          :error="errors.email"
        />

        <UiInput
          v-model="form.password"
          :label="mode === 'signIn' ? 'Password' : 'Create password'"
          type="password"
          :placeholder="mode === 'signIn' ? 'Enter your password' : 'Choose a password'"
          :error="errors.password"
        />

        <UiCheckbox
          v-if="mode === 'signIn'"
          v-model="form.rememberMe"
          label="Remember me"
        />

        <UiButton type="submit" :loading="loading" full-width>
          {{
            loading
              ? mode === 'signIn'
                ? 'Signing in...'
                : 'Creating account...'
              : mode === 'signIn'
                ? 'Sign in'
                : 'Sign up'
          }}
        </UiButton>

        <div v-if="loading" class="loading-state">
          <UiLoader size="sm" label="Authorizing user" />
          <span>Authorizing...</span>
        </div>

        <p v-if="notice" class="notice">{{ notice }}</p>
        <p v-if="errorMessage" class="error">{{ errorMessage }}</p>
      </form>
    </section>
  </main>
</template>

<style scoped>
.auth-page {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 24px;
  background: linear-gradient(180deg, #f3f6ff 0%, #f9fafb 45%, #ffffff 100%);
}

.auth-card {
  width: min(100%, 420px);
  padding: 28px;
  border: 1px solid #e2e8f0;
  border-radius: 16px;
  background-color: #ffffff;
  box-shadow: 0 10px 35px rgba(15, 23, 42, 0.08);
}

.auth-caption {
  margin: 0 0 6px;
  color: #4f46e5;
  font-size: 0.82rem;
  font-weight: 700;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}

.auth-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
}

h1 {
  margin: 0;
  color: #111827;
  font-size: 1.65rem;
}

.auth-subtitle {
  margin: 8px 0 20px;
  color: #6b7280;
}

.auth-hint {
  margin: -8px 0 16px;
  color: #4b5563;
  font-size: 0.85rem;
}

.auth-form {
  display: grid;
  gap: 14px;
}

.auth-signup-extra {
  display: grid;
  gap: 14px;
}

.auth-field {
  display: grid;
  gap: 6px;
}

.auth-field__label {
  color: #0f172a;
  font-size: 0.9rem;
  font-weight: 600;
}

.auth-field__error {
  font-size: 0.83rem;
  color: #dc2626;
}

.auth-field__input {
  width: 100%;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
  padding: 10px 12px;
  font: inherit;
  outline: none;
}

.auth-field__input:focus {
  border-color: rgba(79, 70, 229, 0.4);
  box-shadow: 0 0 0 4px rgba(79, 70, 229, 0.12);
}

.loading-state {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  color: #475569;
  font-size: 0.9rem;
}

.notice {
  margin: 2px 0 0;
  color: #0f766e;
  font-size: 0.9rem;
}

.error {
  margin: 2px 0 0;
  color: #dc2626;
  font-size: 0.9rem;
}
</style>
